name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_push:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
    - name: Login to Azure container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.DOCKER_REGISTRY_URL }}
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
    
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: "${{ vars.DOCKER_REGISTRY_URL }}/${{ vars.IMAGE_NAME }}"
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}