# This workflow will install Python dependencies (via UV), run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  lint_and_test:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Run linter (ruff)
      uses: astral-sh/ruff-action@v3
      with:
        src: "./src"

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
          version: "0.7.8"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"

    - name: Run tests
      # For example, using `pytest`
      run: uv run pytest ./tests

  docker_publish:
    needs: lint_and_test
    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: solar-panel-processor

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t my-image:latest .

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag $IMAGE_NAME:latest ${{ secrets.DOCKER_REGISTRY_URL }}/$IMAGE_NAME:latest
          docker push ${{ secrets.DOCKER_REGISTRY_URL }}/$IMAGE_NAME:latest
